# Generated by Django 5.1.5 on 2025-01-24 20:54

from django.db import migrations, models

#ця міграція використовувалася для створення таблиць 2ї бд ""державного реєстру""
#логічно вона не є продовженням 1ї міграції (призначеної для основної бд)
#що було досягнуто запуском 1ї міграції з опцією --fake перед запуском даної

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='Individual_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.TextField()),
                ('document_type', models.PositiveSmallIntegerField()),
                ('photo_file', models.BinaryField()),
                ('photo_type', models.CharField(max_length=127)),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.TextField()),
                ('document_type', models.PositiveSmallIntegerField()),
                ('official_name', models.CharField(max_length=255)),
            ],
        ),
    ]
