# Generated by Django 5.1.5 on 2025-01-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_individual_record_organization_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points_given',
            field=models.IntegerField(default=10),
        ),
    ]
