# Generated by Django 5.1.5 on 2025-01-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_task_people_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_needed_skill',
            name='skill_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.predefined_skill'),
        ),
    ]
