# Generated by Django 5.1.5 on 2025-01-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_health_vulnerability_proof_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual_record',
            name='photo_file',
        ),
        migrations.RemoveField(
            model_name='individual_record',
            name='photo_type',
        ),
        migrations.AddField(
            model_name='individual_record',
            name='photo_url',
            field=models.URLField(null=True),
        ),
    ]
